name: Legal

on:
  pull_request_target:

jobs:
  cla:
    uses: MetOffice/growss/.github/workflows/cla-check.yaml@main
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    with:
      runner: 'ubuntu-latest'
